# Generated by Django 3.1.3 on 2021-01-21 15:18

import api_v1.models.sneaker
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=180, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('picture', models.ImageField(upload_to=api_v1.models.sneaker.sneaker_image_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='api_v1.brand')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers_on_sale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sneaker',
            },
        ),
        migrations.CreateModel(
            name='SneakerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField()),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_variants', to='api_v1.sneaker')),
            ],
            options={
                'verbose_name': 'SneakerVariant',
                'verbose_name_plural': 'SneakerVariants',
            },
        ),
    ]
