# Generated by Django 3.1.3 on 2021-01-15 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
