# Generated by Django 3.1.3 on 2021-01-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20210115_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='temp_id',
            new_name='id',
        ),
    ]
