# Generated by Django 3.1.3 on 2021-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20210115_1952'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sneaker',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
