# Generated by Django 3.1.3 on 2021-01-15 19:54

import api_v1.models.sneaker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_auto_20210115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='picture',
            field=models.ImageField(default='mydefault', upload_to=api_v1.models.sneaker.sneaker_image_path),
            preserve_default=False,
        ),
    ]
