# Generated by Django 3.1.3 on 2021-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('slr', 'seller'), ('grt', 'guarantor'), ('adm', 'admin'), ('bsc', 'basic')], default='bsc', max_length=16),
        ),
    ]
